#!/bin/bash

# Colors
BLUE='\033[34m'
GREEN='\033[32m'
RED='\033[31m'
YELLOW='\033[33m'
NC='\033[0m' # No Color

cd "$(dirname "$0")/.."

echo -e "\n${YELLOW}> Running tests with coverage :${NC}\n"

pytest
pytest_exit=$?

if [ $pytest_exit -eq 0 ]; then
  echo -e "\n${BLUE}[pytest]${NC} ${GREEN}✓ Done.${NC}\n"
else
  echo -e "\n${BLUE}[pytest]${NC} ${RED}✗ Failed.${NC}\n"
fi

exit $pytest_exit
