---
name: Validate with hassfest

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  validate-hassfest:
    if: github.actor != 'dependabot[bot]'
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - uses: "home-assistant/actions/hassfest@master"
