---
name: Validate for HACS

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  validate-hacs:
    if: github.actor != 'dependabot[bot]'
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
